source 'https://rubygems.org' do
  gem 'puma'
  gem 'sinatra'
  gem 'redis'
  gem 'sequel'
  gem 'sqlite3'

  gem 'ddtrace', path: '/vendor/dd-trace-rb'
  gem 'pry'

  # For profiling
  gem 'ffi'
  gem 'google-protobuf'
end
