require 'datadog/demo_env'

source 'https://rubygems.org' do
  gem 'rack'
  gem 'dogstatsd-ruby'

  gem 'ffi'
  gem 'google-protobuf'

  # Choose correct specs for demo environment
  Datadog::DemoEnv.gem_spec('ddtrace') do |spec|
    if !spec.empty?
      gem 'ddtrace', *spec
    else
      # Install the latest prerelease by default
      source 'http://gems.datadoghq.com/prerelease' do
        gem 'ddtrace', '0.43.0.feature.profiling.98496'
      end
    end
  end

  # Switch to this when profiling goes mainline
  # gem 'ddtrace', *Datadog::DemoEnv.gem_spec('ddtrace')

  # Development
  gem 'pry-stack_explorer', platform: :ruby
  # gem 'rbtrace'
  # gem 'ruby-prof'
end
