version: '3.2'
services:
  app:
    image: ${APP_IMAGE}
    # build:
    #   context: .
    #   args:
    #     BASE_IMAGE: ${BASE_IMAGE}
  tester:
    image: ${APP_IMAGE}
    # build:
    #   context: .
    #   args:
    #     BASE_IMAGE: ${BASE_IMAGE}
  ddagent:
    environment:
      - DD_API_KEY=invalid_api_key
